### ISSUE TITLE
Theme does not apply (maybe only for bg colors)

### ISSUE THREAD

**Issue by balibou** [danmindru/page-ui#6]
I want to reproduce [ScreenshotTwo template](https://shipixen.com/demo/landing-page-templates/template/screenshot-two)

- I follow all the [installation steps](https://pageui.shipixen.com/docs/installation/nextjs) (apart fonts)
- I apply the good theme in `data/config/color.js`

```js
/* Configure colors at https://shipixen.com/color-theme-explorer-shadcn */
const colors = {
  primary: {
    lighter: "#7dd3fc",
    light: "#38bdf8",
    main: "#0ea5e9",
    dark: "#0284c7",
    darker: "#0369a1",
  },
  secondary: {
    lighter: "#a5b4fc",
    light: "#818cf8",
    main: "#6366f1",
    dark: "#4f46e5",
    darker: "#4338ca",
  },
};

module.exports = { colors };

```
I end up with this result:

<img width="1792" alt="Screenshot 2024-07-31 at 21 28 03" src="https://github.com/user-attachments/assets/d2dee9ff-7533-43af-900b-e3bbc5e600f5">

I was expecting this result:

<img width="1792" alt="Screenshot 2024-07-31 at 21 28 36" src="https://github.com/user-attachments/assets/e1f3908b-84c5-4a39-8d96-f6e976112fb1">

I suspect all your landing components to have fixed bg color. For example in this code, with [LandingPrimaryCta](https://github.com/danmindru/page-ui/blob/cd7b36e849db286a077a6e02a3d5271d6d164cd0/components/landing/cta/LandingPrimaryCta.tsx#L126)

[
<img width="589" alt="Screenshot 2024-07-31 at 22 25 08" src="https://github.com/user-attachments/assets/feabd5b4-d5ff-46bb-b570-0a5a59e0e596">
](url)

**Comment by danmindru** [comment]
hey @balibou,

Two things.

### 1. Is it perhaps the dark mode that is the issue here?
By default, TailwindCSS applied dark mode based on the system preference.

I think a better default might be to apply it based on a class.

Can you try adding this to your `tailwind.config.js`?

```js
module.exports = {
   darkMode: ['class'],
   ...
}
```

### 2. Depending on the template, the cta might not have a background

You might need to add the `withBackground` prop to it?
See https://pageui.shipixen.com/docs/landing-page-components/primary-image-cta#with-background

You can swap between primary and secondary backgrounds by setting e.g. `variant="secondary"`

I hope that helps, otherwise let me know if I misunderstood the issue!

**Comment by danmindru** [comment]
Hi @balibou, 
Thanks for the additional information.

Was it the [manual setup](https://pageui.shipixen.com/docs/installation/manual-reactjs) that you tried to follow?

In step 3, the tailwind config file is linked with all the necessary settings.

If you have any suggestions on how to make the documentation better, please let me know!

**Comment by danmindru** [comment]
hi @balibou.

The install command should have added that. I wonder if it skipped replacing the tailwind file because you had one already.

I added some help in the CLI - if some files cannot be copied you get a link to where you can get them.

If you have any other suggestions please
![CleanShot 2024-08-04 at 21 58 08@2x](https://github.com/user-attachments/assets/8719848a-c361-48f9-8a51-8837a1e73add)
 let me know!

**Comment by balibou** [comment]
Hey @danmindru  Thanks for your reply !
Indeed there was a tailwind config that was generated but there was only in content prop:

```js
"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
```
